<?php
namespace App\Http\Controllers\Api\Member\Qualifications;
use App\Http\Controllers\Controller; use App\Http\Requests\Qualifications\StartQualificationAssessmentRequest; use App\Models\Member; use App\Models\QualificationAssessment; use App\Models\QualificationFramework; use App\Services\Qualifications\QualificationAssessmentService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class MyQualificationAssessmentController extends Controller
{
    private function member(Request $r):Member{return Member::query()->where('user_id',$r->user()->id)->firstOrFail();}
    public function index(Request $r):JsonResponse{return response()->json(['data'=>$this->member($r)->qualificationAssessments()->with(['framework','targetLevel'])->latest()->get(),'disclaimer'=>config('qualification.disclaimer')]);}
    public function show(Request $r,QualificationAssessment $assessment):JsonResponse{$m=$this->member($r);abort_unless($assessment->member_id===$m->id,403);return response()->json(['data'=>$assessment->load(['framework','targetLevel','results.requirement','recommendations']),'disclaimer'=>config('qualification.disclaimer')]);}
    public function store(StartQualificationAssessmentRequest $r,QualificationAssessmentService $service):JsonResponse{$m=$this->member($r);$framework=QualificationFramework::findOrFail($r->validated('framework_id'));abort_unless($framework->assessment_enabled && $framework->governance_status==='published',422,'This framework is reference-only until validated assessment rules are published.');$levelId=$r->validated('target_level_id');if($levelId)abort_unless($framework->levels()->whereKey($levelId)->exists(),422,'Target level does not belong to selected framework.');$assessment=$m->qualificationAssessments()->create(['framework_id'=>$framework->id,'target_level_id'=>$levelId,'status'=>'draft']);return response()->json(['data'=>$service->evaluate($assessment),'disclaimer'=>config('qualification.disclaimer')],201);}
    public function refresh(Request $r,QualificationAssessment $assessment,QualificationAssessmentService $service):JsonResponse{$m=$this->member($r);abort_unless($assessment->member_id===$m->id,403);abort_if(in_array($assessment->status,['submitted','under_review','assessed'],true),422,'Submitted assessments cannot be refreshed.');return response()->json(['data'=>$service->evaluate($assessment),'disclaimer'=>config('qualification.disclaimer')]);}
    public function submit(Request $r,QualificationAssessment $assessment,QualificationAssessmentService $service):JsonResponse{$m=$this->member($r);abort_unless($assessment->member_id===$m->id,403);$data=$r->validate(['member_note'=>['nullable','string','max:4000']]);return response()->json(['data'=>$service->submit($assessment,$data['member_note']??null),'disclaimer'=>config('qualification.disclaimer')]);}
}
