<?php
namespace Tests\Feature;
use App\Models\Member; use App\Models\PortfolioCompetency; use App\Models\QualificationFramework; use App\Models\QualificationRequirement; use App\Models\Role; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class QualificationFrameworkTest extends TestCase
{
    use RefreshDatabase;
    protected function setUp():void{parent::setUp();$this->seed(\Database\Seeders\RolePermissionSeeder::class);}
    private function memberUser():array{$u=User::factory()->create(['email_verified_at'=>now()]);$u->roles()->attach(Role::where('code','member')->first());$m=Member::create(['user_id'=>$u->id,'member_no'=>'NL-2026-'.str_pad((string)(Member::count()+1),6,'0',STR_PAD_LEFT),'status'=>'active','joined_at'=>now()]);return[$u,$m];}
    private function framework():QualificationFramework{$f=QualificationFramework::create(['code'=>'TEST-QF','name'=>'Test Evidence Framework','scope'=>'internal','governance_status'=>'published','assessment_enabled'=>true]);$f->levels()->create(['ordinal'=>1,'code'=>'L1','title'=>'Level 1']);return$f;}
    public function test_reference_only_framework_cannot_be_assessed():void{[$u,$m]=$this->memberUser();$f=QualificationFramework::create(['code'=>'REF','name'=>'Reference Only','scope'=>'national','governance_status'=>'reference_only','assessment_enabled'=>false]);$this->actingAs($u)->postJson('/api/qualification-assessments',['framework_id'=>$f->id])->assertStatus(422);}
    public function test_requirement_is_met_only_when_configured_evidence_exists():void{[$u,$m]=$this->memberUser();$f=$this->framework();$level=$f->levels()->first();QualificationRequirement::create(['framework_id'=>$f->id,'framework_level_id'=>$level->id,'code'=>'COMP-1','category'=>'competency','title'=>'Critical Care Competency','mandatory'=>true,'weight'=>2,'minimum_trust_level'=>3,'evidence_rule'=>['source'=>'competency','filters'=>['name'=>'Critical Care Nursing'],'minimum_count'=>1],'governance_status'=>'published']);PortfolioCompetency::create(['member_id'=>$m->id,'domain'=>'Patient Care','name'=>'Critical Care Nursing','proficiency'=>'advanced','evidence_state'=>'document_supported']);$r=$this->actingAs($u)->postJson('/api/qualification-assessments',['framework_id'=>$f->id,'target_level_id'=>$level->id])->assertCreated();$r->assertJsonPath('data.requirements_met',1)->assertJsonPath('data.requirements_gap',0);}
    public function test_self_declared_evidence_can_be_partial_when_verified_evidence_is_required():void{[$u,$m]=$this->memberUser();$f=$this->framework();QualificationRequirement::create(['framework_id'=>$f->id,'code'=>'COMP-2','category'=>'competency','title'=>'Verified Competency','mandatory'=>true,'weight'=>1,'minimum_trust_level'=>5,'evidence_rule'=>['source'=>'competency','filters'=>['name'=>'Medication Administration']],'governance_status'=>'published']);PortfolioCompetency::create(['member_id'=>$m->id,'domain'=>'Patient Care','name'=>'Medication Administration','proficiency'=>'competent','evidence_state'=>'self_declared']);$r=$this->actingAs($u)->postJson('/api/qualification-assessments',['framework_id'=>$f->id])->assertCreated();$r->assertJsonPath('data.requirements_partial',1);}
    public function test_framework_comparison_does_not_infer_equivalence_without_published_crosswalk():void{[$u]=$this->memberUser();$a=QualificationFramework::create(['code'=>'A','name'=>'Framework A','governance_status'=>'published']);$b=QualificationFramework::create(['code'=>'B','name'=>'Framework B','governance_status'=>'published']);$this->actingAs($u)->getJson('/api/qualification-frameworks/compare?source_framework_id='.$a->id.'&target_framework_id='.$b->id)->assertOk()->assertJsonPath('data.automatic_equivalence',false)->assertJsonCount(0,'data.approved_crosswalks');}
}
