<?php
namespace App\Http\Controllers\Api\Member\Credentials;
use App\Http\Controllers\Controller; use App\Http\Requests\Credentials\UploadMemberDocumentRequest; use App\Models\Member; use App\Models\MemberDocument; use App\Services\AuditLogger; use App\Services\Credentials\MemberDocumentStorageService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Symfony\Component\HttpFoundation\StreamedResponse;
class MemberDocumentController extends Controller
{
    public function index(Request $request):JsonResponse{$m=$this->member($request);return response()->json(['data'=>$m->documents()->latest()->get()]);}
    public function store(UploadMemberDocumentRequest $request,MemberDocumentStorageService $storage,AuditLogger $audit):JsonResponse{$m=$this->member($request);$doc=$storage->store($m,$request->user(),$request->file('file'),$request->string('document_type')->toString(),$request->input('title'),$request->input('issued_on'),$request->input('expires_on'));$audit->write('member_document.uploaded',$request->user(),'member_document',$doc->id,['document_type'=>$doc->document_type,'sha256'=>$doc->sha256],$request);return response()->json(['data'=>$doc],201);}
    public function download(Request $request,MemberDocument $document):StreamedResponse{$m=$this->member($request);abort_unless($document->member_id===$m->id,403);abort_unless($document->security_status==='clean',423,'Document security scan must complete before download.');return Storage::disk($document->storage_disk)->download($document->storage_path,$document->original_name);}
    public function destroy(Request $request,MemberDocument $document,AuditLogger $audit):JsonResponse{$m=$this->member($request);abort_unless($document->member_id===$m->id,403);abort_if($document->source_application_document_id,409,'Approved application evidence is retained as an immutable source document.');abort_if($document->credentials()->exists(),409,'Document is linked to a credential and cannot be deleted.');Storage::disk($document->storage_disk)->delete($document->storage_path);$audit->write('member_document.deleted',$request->user(),'member_document',$document->id,['title'=>$document->title],$request);$document->delete();return response()->json([],204);}
    private function member(Request $r):Member{return Member::query()->where('user_id',$r->user()->id)->firstOrFail();}
}
