<?php
namespace App\Http\Controllers\Api\Admin\Organization;
use App\Http\Controllers\Controller; use App\Http\Requests\Organization\StoreInitiativeRequest; use App\Models\Initiative; use App\Models\InitiativeBeneficiary; use App\Models\InitiativeBudgetLine; use App\Models\InitiativeMilestone; use App\Models\InitiativePartner; use App\Models\InitiativeUpdate; use App\Services\AuditLogger; use App\Services\IdentifierService; use App\Services\Organization\BudgetSummaryService; use App\Services\Organization\InitiativeProgressService; use App\Services\Organization\OrganizationCommunicationService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class InitiativeAdminController extends Controller {
 public function __construct(private IdentifierService $ids,private AuditLogger $audit,private InitiativeProgressService $progress,private BudgetSummaryService $budget,private OrganizationCommunicationService $communications){}
 public function index(Request $r){$q=Initiative::query()->withCount(['milestones','partners','beneficiaries'])->with('owner:id,name,email');if($r->filled('type'))$q->where('type',$r->string('type'));if($r->filled('status'))$q->where('status',$r->string('status'));if($r->filled('q')){$s='%'.$r->string('q').'%';$q->where(fn($x)=>$x->where('title','like',$s)->orWhere('initiative_no','like',$s));}return response()->json($q->latest()->paginate(25));}
 public function store(StoreInitiativeRequest $r){$d=$r->validated();$i=Initiative::query()->create($d+['initiative_no'=>$this->ids->next('initiative','NLP'),'status'=>$d['status']??'proposed','budget_currency'=>$d['budget_currency']??config('organization.default_currency','PHP'),'owner_user_id'=>$d['owner_user_id']??$r->user()->id,'visibility'=>$d['visibility']??'members']);$this->audit->write('initiative.created',$r->user(),'initiative',$i->id,['initiative_no'=>$i->initiative_no,'type'=>$i->type]);return response()->json($i,201);}
 public function show(Initiative $initiative){return response()->json(['initiative'=>$initiative->load(['owner:id,name,email','milestones'=>fn($q)=>$q->orderBy('sort_order'),'partners','beneficiaries','budgetLines','updates'=>fn($q)=>$q->latest('published_at'),'documents']),'budget'=>$this->budget->summarize($initiative)]);}
 public function update(StoreInitiativeRequest $r,Initiative $initiative){$initiative->update($r->validated());$this->audit->write('initiative.updated',$r->user(),'initiative',$initiative->id,['initiative_no'=>$initiative->initiative_no]);return response()->json($initiative->refresh());}
 public function publish(Request $r,Initiative $initiative){$d=$r->validate(['visibility'=>['required',Rule::in(['members','public'])]]);$initiative->update(['visibility'=>$d['visibility'],'published_at'=>now()]);$this->audit->write('initiative.published',$r->user(),'initiative',$initiative->id,['visibility'=>$d['visibility']]);return response()->json($initiative->refresh());}
 public function milestone(Request $r,Initiative $initiative){$d=$r->validate(['title'=>'required|string|max:255','description'=>'nullable|string|max:5000','status'=>['nullable',Rule::in(['planned','in_progress','completed','blocked'])],'due_on'=>'nullable|date','weight'=>'nullable|numeric|min:0|max:100','sort_order'=>'nullable|integer|min:0']);$m=$initiative->milestones()->create($d+['status'=>$d['status']??'planned','weight'=>$d['weight']??1]);$this->progress->refresh($initiative);return response()->json($m,201);}
 public function updateMilestone(Request $r,InitiativeMilestone $milestone){$d=$r->validate(['title'=>'sometimes|required|string|max:255','description'=>'nullable|string|max:5000','status'=>['sometimes',Rule::in(['planned','in_progress','completed','blocked'])],'due_on'=>'nullable|date','weight'=>'nullable|numeric|min:0|max:100','sort_order'=>'nullable|integer|min:0']);if(($d['status']??null)==='completed'&&!$milestone->completed_at)$d['completed_at']=now();if(($d['status']??null)&&$d['status']!=='completed')$d['completed_at']=null;$milestone->update($d);$this->progress->refresh($milestone->initiative);return response()->json($milestone->refresh());}
 public function partner(Request $r,Initiative $initiative){$d=$r->validate(['name'=>'required|string|max:255','partner_type'=>'nullable|string|max:100','role'=>'nullable|string|max:255','country'=>'nullable|string|max:100','notes'=>'nullable|string|max:5000']);return response()->json($initiative->partners()->create($d),201);}
 public function beneficiary(Request $r,Initiative $initiative){$d=$r->validate(['category'=>'required|string|max:255','target_count'=>'nullable|integer|min:0','actual_count'=>'nullable|integer|min:0','geography'=>'nullable|string|max:255','notes'=>'nullable|string|max:5000']);return response()->json($initiative->beneficiaries()->create($d+['target_count'=>$d['target_count']??0,'actual_count'=>$d['actual_count']??0]),201);}
 public function budgetLine(Request $r,Initiative $initiative){abort_unless($r->user()->hasPermission('program.finance.manage'),403);$d=$r->validate(['category'=>'required|string|max:120','description'=>'required|string|max:255','planned_amount'=>'nullable|numeric|min:0','committed_amount'=>'nullable|numeric|min:0','spent_amount'=>'nullable|numeric|min:0']);$line=$initiative->budgetLines()->create($d);$this->audit->write('initiative.budget_updated',$r->user(),'initiative',$initiative->id,['line_id'=>$line->id]);return response()->json(['line'=>$line,'budget'=>$this->budget->summarize($initiative)],201);}
 public function updatePost(Request $r,Initiative $initiative){$d=$r->validate(['title'=>'required|string|max:255','body'=>'required|string|max:10000','update_type'=>'nullable|string|max:80','notify_members'=>'nullable|boolean','audience_filters'=>'nullable|array']);if(($d['notify_members']??false)&&empty($d['audience_filters']))return response()->json(['message'=>'Explicit audience_filters are required when notifying members.'],422);return DB::transaction(function()use($r,$initiative,$d){$u=$initiative->updates()->create(['title'=>$d['title'],'body'=>$d['body'],'update_type'=>$d['update_type']??'progress','notify_members'=>$d['notify_members']??false,'audience_filters'=>$d['audience_filters']??null,'created_by'=>$r->user()->id,'published_at'=>now()]);$notified=($d['notify_members']??false)?$this->communications->initiativeUpdate($initiative,$u,$d['audience_filters']):0;$this->audit->write('initiative.update_published',$r->user(),'initiative',$initiative->id,['update_id'=>$u->id,'notified'=>$notified]);return response()->json(['update'=>$u,'notifications_queued'=>$notified],201);});}
 public function refresh(Initiative $initiative){$i=$this->progress->refresh($initiative);return response()->json(['initiative'=>$i,'budget'=>$this->budget->summarize($i)]);}
}
