<?php
namespace App\Http\Controllers\Api\Admin\Organization;
use App\Http\Controllers\Controller; use App\Http\Requests\Organization\StorePolicyRequest; use App\Models\PolicyRecord; use App\Services\AuditLogger; use App\Services\IdentifierService; use App\Services\Organization\PolicyLifecycleService; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class PolicyAdminController extends Controller {
 public function __construct(private IdentifierService $ids,private AuditLogger $audit,private PolicyLifecycleService $lifecycle){}
 public function index(Request $r){$q=PolicyRecord::query()->with('owner:id,name,email')->withCount(['stageEvents','stakeholders']);if($r->filled('status'))$q->where('status',$r->string('status'));if($r->filled('q')){$s='%'.$r->string('q').'%';$q->where(fn($x)=>$x->where('title','like',$s)->orWhere('policy_no','like',$s));}return response()->json($q->latest()->paginate(25));}
 public function store(StorePolicyRequest $r){$d=$r->validated();$p=PolicyRecord::query()->create($d+['policy_no'=>$this->ids->next('policy','NLPL'),'status'=>'proposed','owner_user_id'=>$d['owner_user_id']??$r->user()->id,'visibility'=>$d['visibility']??'members']);$this->audit->write('policy.created',$r->user(),'policy_record',$p->id,['policy_no'=>$p->policy_no]);return response()->json($p,201);}
 public function show(PolicyRecord $policy){return response()->json($policy->load(['owner:id,name,email','stageEvents'=>fn($q)=>$q->latest('occurred_at'),'stakeholders','documents']));}
 public function update(StorePolicyRequest $r,PolicyRecord $policy){$policy->update($r->validated());$this->audit->write('policy.updated',$r->user(),'policy_record',$policy->id,['policy_no'=>$policy->policy_no]);return response()->json($policy->refresh());}
 public function transition(Request $r,PolicyRecord $policy){$d=$r->validate(['status'=>['required',Rule::in(config('organization.policy_statuses'))],'note'=>'nullable|string|max:10000','notify_members'=>'nullable|boolean','audience_filters'=>'nullable|array']);if(($d['notify_members']??false)&&empty($d['audience_filters']))return response()->json(['message'=>'Explicit audience_filters are required when notifying members.'],422);return response()->json($this->lifecycle->transition($policy,$d['status'],$r->user(),$d['note']??null,$d['notify_members']??false,$d['audience_filters']??[]));}
 public function stakeholder(Request $r,PolicyRecord $policy){$d=$r->validate(['name'=>'required|string|max:255','stakeholder_type'=>'nullable|string|max:120','position'=>'nullable|string|max:255','engagement_status'=>'nullable|string|max:80','notes'=>'nullable|string|max:5000']);return response()->json($policy->stakeholders()->create($d),201);}
 public function publish(Request $r,PolicyRecord $policy){$d=$r->validate(['visibility'=>['required',Rule::in(['members','public'])]]);$policy->update(['visibility'=>$d['visibility'],'published_at'=>now()]);$this->audit->write('policy.published',$r->user(),'policy_record',$policy->id,['visibility'=>$d['visibility']]);return response()->json($policy->refresh());}
}
