<?php
namespace App\Http\Controllers\Api\Admin\Qualifications;
use App\Http\Controllers\Controller; use App\Models\QualificationFramework; use App\Models\QualificationFrameworkLevel; use App\Models\QualificationRequirement; use App\Models\FrameworkLevelCrosswalk; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class FrameworkAdminController extends Controller
{
    public function index():JsonResponse{return response()->json(['data'=>QualificationFramework::with(['levels','requirements'])->orderBy('name')->get()]);}
    public function updateFramework(Request $r,QualificationFramework $framework):JsonResponse{$d=$r->validate(['name'=>['sometimes','string','max:180'],'version_label'=>['nullable','string','max:100'],'governance_status'=>['sometimes','in:draft,reference_only,published,retired'],'assessment_enabled'=>['sometimes','boolean'],'description'=>['nullable','string'],'governance_note'=>['nullable','string'],'source_url'=>['nullable','url'],'effective_from'=>['nullable','date'],'effective_to'=>['nullable','date','after_or_equal:effective_from']]);if(($d['assessment_enabled']??false)===true)abort_unless(($d['governance_status']??$framework->governance_status)==='published',422,'Assessment can be enabled only for a published framework.');if(($d['governance_status']??null)==='published'){$d['validated_by']=$r->user()->id;$d['validated_at']=now();}$framework->update($d);return response()->json(['data'=>$framework->fresh(['levels','requirements'])]);}
    public function storeLevel(Request $r,QualificationFramework $framework):JsonResponse{$d=$r->validate(['ordinal'=>['required','integer','between:1,100'],'code'=>['required','string','max:40'],'title'=>['required','string','max:120'],'descriptors'=>['nullable','array']]);$row=$framework->levels()->create($d);$framework->update(['level_count'=>$framework->levels()->count()]);return response()->json(['data'=>$row],201);}
    public function storeRequirement(Request $r,QualificationFramework $framework):JsonResponse{$d=$r->validate(['framework_level_id'=>['nullable','uuid'],'code'=>['required','string','max:80'],'category'=>['required','in:education,credential,competency,experience,cpd,language,technology,other'],'title'=>['required','string','max:180'],'description'=>['nullable','string'],'mandatory'=>['sometimes','boolean'],'weight'=>['nullable','numeric','min:0.01','max:100'],'minimum_trust_level'=>['required','integer','between:0,5'],'evidence_rule'=>['required','array'],'governance_status'=>['required','in:draft,published,retired'],'governance_note'=>['nullable','string']]);if(!empty($d['framework_level_id']))abort_unless($framework->levels()->whereKey($d['framework_level_id'])->exists(),422,'Level does not belong to framework.');$row=$framework->requirements()->create($d);return response()->json(['data'=>$row],201);}
    public function updateRequirement(Request $r,QualificationRequirement $requirement):JsonResponse{$d=$r->validate(['title'=>['sometimes','string','max:180'],'description'=>['nullable','string'],'mandatory'=>['sometimes','boolean'],'weight'=>['sometimes','numeric','min:0.01','max:100'],'minimum_trust_level'=>['sometimes','integer','between:0,5'],'evidence_rule'=>['sometimes','array'],'governance_status'=>['sometimes','in:draft,published,retired'],'governance_note'=>['nullable','string']]);$requirement->update($d);return response()->json(['data'=>$requirement->fresh()]);}
    public function storeCrosswalk(Request $r):JsonResponse{$d=$r->validate(['source_level_id'=>['required','uuid','exists:qualification_framework_levels,id'],'target_level_id'=>['required','uuid','different:source_level_id','exists:qualification_framework_levels,id'],'mapping_type'=>['required','in:reference,approximate,officially_recognized'],'governance_status'=>['required','in:draft,published,retired'],'basis_note'=>['nullable','string'],'source_url'=>['nullable','url']]);$source=QualificationFrameworkLevel::findOrFail($d['source_level_id']);$target=QualificationFrameworkLevel::findOrFail($d['target_level_id']);abort_if($source->framework_id===$target->framework_id,422,'Crosswalk levels must belong to different frameworks.');if($d['governance_status']==='published'){$d['validated_by']=$r->user()->id;$d['validated_at']=now();}$row=FrameworkLevelCrosswalk::query()->create($d);return response()->json(['data'=>$row],201);}
}
