<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('initiatives',function(Blueprint $t){$t->uuid('id')->primary();$t->string('initiative_no')->unique();$t->string('type');$t->string('title');$t->text('summary')->nullable();$t->string('status')->default('proposed');$t->decimal('progress_percent',5,2)->default(0);$t->date('starts_on')->nullable();$t->date('ends_on')->nullable();$t->string('lead_committee')->nullable();$t->foreignUuid('owner_user_id')->nullable()->constrained('users')->nullOnDelete();$t->decimal('budget_total',14,2)->default(0);$t->string('budget_currency',3)->default('PHP');$t->string('visibility')->default('members');$t->json('audience_filters')->nullable();$t->text('outcome_summary')->nullable();$t->timestamp('published_at')->nullable();$t->timestamps();$t->index(['type','status']);$t->index(['visibility','published_at']);});
  Schema::create('initiative_milestones',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('initiative_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('description')->nullable();$t->string('status')->default('planned');$t->date('due_on')->nullable();$t->decimal('weight',6,2)->default(1);$t->timestamp('completed_at')->nullable();$t->unsignedInteger('sort_order')->default(0);$t->timestamps();$t->index(['initiative_id','status']);});
  Schema::create('initiative_partners',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('initiative_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('partner_type')->nullable();$t->string('role')->nullable();$t->string('country')->nullable();$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('initiative_beneficiaries',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('initiative_id')->constrained()->cascadeOnDelete();$t->string('category');$t->unsignedInteger('target_count')->default(0);$t->unsignedInteger('actual_count')->default(0);$t->string('geography')->nullable();$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('initiative_budget_lines',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('initiative_id')->constrained()->cascadeOnDelete();$t->string('category');$t->string('description');$t->decimal('planned_amount',14,2)->default(0);$t->decimal('committed_amount',14,2)->default(0);$t->decimal('spent_amount',14,2)->default(0);$t->timestamps();$t->index(['initiative_id','category']);});
  Schema::create('initiative_updates',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('initiative_id')->constrained()->cascadeOnDelete();$t->string('title');$t->text('body');$t->string('update_type')->default('progress');$t->boolean('notify_members')->default(false);$t->json('audience_filters')->nullable();$t->foreignUuid('created_by')->constrained('users')->restrictOnDelete();$t->timestamp('published_at')->nullable();$t->timestamps();$t->index(['initiative_id','published_at']);});
  Schema::create('initiative_documents',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('initiative_id')->constrained()->cascadeOnDelete();$t->string('title');$t->string('document_type')->default('supporting');$t->string('original_name');$t->string('storage_disk')->default('private');$t->text('storage_path');$t->string('mime_type');$t->unsignedBigInteger('size_bytes');$t->string('sha256',64);$t->string('security_status')->default('pending');$t->string('visibility')->default('internal');$t->foreignUuid('uploaded_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
  Schema::create('policy_records',function(Blueprint $t){$t->uuid('id')->primary();$t->string('policy_no')->unique();$t->string('title');$t->string('issue_area')->nullable();$t->text('objective')->nullable();$t->text('position_summary')->nullable();$t->string('status')->default('proposed');$t->string('lead_committee')->nullable();$t->string('target_body')->nullable();$t->foreignUuid('owner_user_id')->nullable()->constrained('users')->nullOnDelete();$t->string('visibility')->default('members');$t->json('audience_filters')->nullable();$t->timestamp('submitted_at')->nullable();$t->timestamp('adopted_at')->nullable();$t->timestamp('published_at')->nullable();$t->timestamps();$t->index(['status','issue_area']);$t->index(['visibility','published_at']);});
  Schema::create('policy_stage_events',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('policy_record_id')->constrained('policy_records')->cascadeOnDelete();$t->string('from_status');$t->string('to_status');$t->text('note')->nullable();$t->timestamp('occurred_at');$t->foreignUuid('changed_by')->constrained('users')->restrictOnDelete();$t->boolean('notify_members')->default(false);$t->json('audience_filters')->nullable();$t->timestamps();$t->index(['policy_record_id','occurred_at']);});
  Schema::create('policy_stakeholders',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('policy_record_id')->constrained('policy_records')->cascadeOnDelete();$t->string('name');$t->string('stakeholder_type')->nullable();$t->string('position')->nullable();$t->string('engagement_status')->default('identified');$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('policy_documents',function(Blueprint $t){$t->uuid('id')->primary();$t->foreignUuid('policy_record_id')->constrained('policy_records')->cascadeOnDelete();$t->string('title');$t->string('document_type')->default('reference');$t->string('original_name');$t->string('storage_disk')->default('private');$t->text('storage_path');$t->string('mime_type');$t->unsignedBigInteger('size_bytes');$t->string('sha256',64);$t->string('security_status')->default('pending');$t->string('visibility')->default('internal');$t->foreignUuid('uploaded_by')->constrained('users')->restrictOnDelete();$t->timestamps();});
 }
 public function down():void{Schema::dropIfExists('policy_documents');Schema::dropIfExists('policy_stakeholders');Schema::dropIfExists('policy_stage_events');Schema::dropIfExists('policy_records');Schema::dropIfExists('initiative_documents');Schema::dropIfExists('initiative_updates');Schema::dropIfExists('initiative_budget_lines');Schema::dropIfExists('initiative_beneficiaries');Schema::dropIfExists('initiative_partners');Schema::dropIfExists('initiative_milestones');Schema::dropIfExists('initiatives');}
};
