<?php
namespace App\Services\Communications;
use App\Jobs\DeliverCampaignRecipient; use App\Models\CommunicationCampaign; use App\Models\CampaignRecipient; use App\Services\IdentifierService; use Illuminate\Support\Carbon; use Illuminate\Support\Facades\DB; use Illuminate\Validation\ValidationException;
class CampaignService {
 public function __construct(private AudienceResolver $audience,private PreferenceService $preferences,private IdentifierService $ids){}
 public function create(array $data,string $creatorId):CommunicationCampaign{return CommunicationCampaign::query()->create(array_merge($data,['campaign_no'=>$this->ids->next('campaign','NLCM'),'created_by'=>$creatorId,'status'=>'draft']));}
 public function materializeAudience(CommunicationCampaign $campaign):int{$users=$this->audience->resolve($campaign->audience_filters??[]);foreach($users as $user){$r=$this->preferences->resolveChannels($user,$campaign->category,$campaign->channels??[]);CampaignRecipient::query()->firstOrCreate(['campaign_id'=>$campaign->id,'user_id'=>$user->id],['resolved_channels'=>$r['resolved'],'suppressed_channels'=>$r['suppressed'],'status'=>'pending']);}return $users->count();}
 public function schedule(CommunicationCampaign $campaign,?string $when=null):CommunicationCampaign{if(!in_array($campaign->status,['draft','scheduled'],true))throw ValidationException::withMessages(['status'=>'Only draft or scheduled campaigns may be scheduled.']);$campaign->update(['status'=>'scheduled','scheduled_at'=>$when?Carbon::parse($when):now()]);return $campaign->fresh();}
 public function dispatch(CommunicationCampaign $campaign):CommunicationCampaign{$campaign=DB::transaction(function()use($campaign){$campaign=CommunicationCampaign::query()->lockForUpdate()->findOrFail($campaign->id);if(!in_array($campaign->status,['draft','scheduled'],true))return $campaign;$campaign->update(['status'=>'processing','started_at'=>now()]);$this->materializeAudience($campaign);$campaign->recipients()->where('status','pending')->update(['status'=>'queued','queued_at'=>now()]);if(!$campaign->recipients()->exists())$campaign->update(['status'=>'completed','completed_at'=>now()]);return $campaign->fresh();},3);$campaign->recipients()->where('status','queued')->pluck('id')->each(fn($id)=>DeliverCampaignRecipient::dispatch($id));return $campaign->fresh();}
}
