<?php
namespace App\Services\Communications;
use App\Models\ApplicationStatusEvent; use App\Models\CommunicationTriggerEvent; use App\Models\CredentialReminderEvent; use App\Models\EventRegistration; use App\Models\QualificationAssessment; use App\Models\MessageTemplate; use Throwable;
class TriggerBridgeService {
 public function __construct(private DeliveryService $delivery){}
 public function ingest():int{$count=0;
  CredentialReminderEvent::query()->with('member.user','credential')->where('state','queued')->get()->each(function($e)use(&$count){$u=$e->member?->user;if(!$u)return;$count+=$this->make($u->id,'credential_'.$e->reminder_type,'credential_reminder',$e->id,['credential_title'=>$e->credential?->title,'expires_on'=>(string)$e->credential?->expires_on]);});
  ApplicationStatusEvent::query()->with('application.user')->whereIn('to_status',['submitted','returned_for_information','approved','rejected'])->where('created_at','>=',now()->subDays(14))->get()->each(function($e)use(&$count){$u=$e->application?->user;if($u)$count+=$this->make($u->id,'application_'.$e->to_status,'application_status_event',$e->id,['application_no'=>$e->application?->application_no,'note'=>$e->note]);});
  QualificationAssessment::query()->with('member.user','framework')->where('status','assessed')->where('updated_at','>=',now()->subDays(14))->get()->each(function($a)use(&$count){$u=$a->member?->user;if($u)$count+=$this->make($u->id,'qualification_assessed','qualification_assessment',$a->id,['framework'=>$a->framework?->name,'readiness_score'=>$a->readiness_score]);});
  foreach(config('communications.event_reminder_days',[7,1]) as $days){EventRegistration::query()->with('member.user','event')->where('status','registered')->whereHas('event',fn($q)=>$q->where('status','published')->whereBetween('starts_at',[now()->copy()->startOfDay()->addDays($days),now()->copy()->endOfDay()->addDays($days)]))->get()->each(function($r)use(&$count,$days){$u=$r->member?->user;if($u)$count+=$this->make($u->id,'event_reminder_'.$days.'d','event_registration',$r->id,['event_title'=>$r->event?->title,'event_starts_at'=>$r->event?->starts_at?->toIso8601String()]);});}
  return $count;}
 private function make(string $userId,string $eventType,string $sourceType,string $sourceId,array $payload):int{try{$row=CommunicationTriggerEvent::query()->firstOrCreate(['user_id'=>$userId,'event_type'=>$eventType,'source_type'=>$sourceType,'source_id'=>$sourceId],['payload'=>$payload,'status'=>'pending','occurred_at'=>now()]);return $row->wasRecentlyCreated?1:0;}catch(Throwable){return 0;}}
 public function process():int{$processed=0;CommunicationTriggerEvent::query()->with('user')->where('status','pending')->orderBy('occurred_at')->limit(500)->get()->each(function($e)use(&$processed){$template=MessageTemplate::query()->where('code',$e->event_type)->where('governance_status','published')->first();if(!$template){$e->update(['status'=>'suppressed','failure_reason'=>'No published template for trigger.','processed_at'=>now()]);return;}$ctx=array_merge($e->payload??[],['source_type'=>$e->source_type,'source_id'=>$e->source_id,'dedupe_key'=>'trigger:'.$e->id,'action_url'=>$this->actionUrl($e->event_type)]);$outcome=$this->delivery->deliver($e->user,$template->category,$template->subject_template,$template->body_template,['in_app','email'],$ctx);$successful=collect($outcome['results'])->contains(fn($r)=>in_array($r['status']??null,['sent','delivered'],true));$e->update(['status'=>$successful?'processed':'suppressed','processed_at'=>now(),'failure_reason'=>$successful?null:'All configured/requested channels were suppressed or unavailable.']);if($e->source_type==='credential_reminder')CredentialReminderEvent::query()->whereKey($e->source_id)->update($successful?['state'=>'delivered','delivered_at'=>now()]:['state'=>'suppressed','suppressed_at'=>now()]);$processed++;});return $processed;}
 private function actionUrl(string $type):?string{if(str_starts_with($type,'credential_'))return '/credentials';if(str_starts_with($type,'application_'))return '/application';if(str_starts_with($type,'qualification_'))return '/qualifications';if(str_starts_with($type,'event_'))return '/events';if($type==='initiative_update')return '/organization/programs';if($type==='policy_stage_changed')return '/organization/policies';return null;}
}
