<?php
namespace App\Http\Controllers\Api\Member\Portfolio;
use App\Http\Controllers\Controller; use App\Models\Member; use App\Models\PortfolioCompetency; use App\Models\PortfolioLanguage; use App\Models\PortfolioSpecialty; use App\Models\PortfolioTechnologySkill; use App\Services\Portfolio\PortfolioCompletionService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class PortfolioItemController extends Controller
{
    public function specialty(Request $r,PortfolioCompletionService $c):JsonResponse{$d=$r->validate(['name'=>['required','string','max:160'],'level'=>['required','in:developing,experienced,advanced,expert'],'years_experience'=>['nullable','integer','min:0','max:80']]);$m=$this->member($r);$row=$m->specialties()->updateOrCreate(['member_id'=>$m->id,'name'=>$d['name']],$d+['status'=>'self_declared']);$c->refresh($m);return response()->json(['data'=>$row]);}
    public function competency(Request $r,PortfolioCompletionService $c):JsonResponse{$d=$r->validate(['domain'=>['required','string','max:120'],'name'=>['required','string','max:180'],'proficiency'=>['required','in:developing,competent,proficient,advanced,expert']]);$m=$this->member($r);$row=$m->competencies()->updateOrCreate(['member_id'=>$m->id,'domain'=>$d['domain'],'name'=>$d['name']],$d+['evidence_state'=>'self_declared']);$c->refresh($m);return response()->json(['data'=>$row]);}
    public function technology(Request $r,PortfolioCompletionService $c):JsonResponse{$d=$r->validate(['category'=>['required','string','max:120'],'name'=>['required','string','max:180'],'proficiency'=>['required','in:aware,working,proficient,advanced']]);$m=$this->member($r);$row=$m->technologySkills()->updateOrCreate(['member_id'=>$m->id,'category'=>$d['category'],'name'=>$d['name']],$d+['status'=>'self_declared']);$c->refresh($m);return response()->json(['data'=>$row]);}
    public function language(Request $r,PortfolioCompletionService $c):JsonResponse{$d=$r->validate(['language'=>['required','string','max:100'],'speaking'=>['required','in:basic,conversational,professional,native'],'reading'=>['required','in:basic,conversational,professional,native'],'writing'=>['required','in:basic,conversational,professional,native']]);$m=$this->member($r);$row=$m->languages()->updateOrCreate(['member_id'=>$m->id,'language'=>$d['language']],$d+['status'=>'self_declared']);$c->refresh($m);return response()->json(['data'=>$row]);}
    private function member(Request $r):Member{return Member::query()->where('user_id',$r->user()->id)->firstOrFail();}
}
