<?php
namespace App\Http\Controllers\Api\Admin\Communications;
use App\Http\Controllers\Controller; use App\Models\MessageTemplate; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Validation\Rule;
class TemplateController extends Controller {
 public function index(Request $r):JsonResponse{$q=MessageTemplate::query()->orderBy('category')->orderBy('name');if(!$r->user()->hasPermission('settings.manage'))$q->whereNotIn('category',config('communications.mandatory_categories',[]));return response()->json(['data'=>$q->get()]);}
 public function store(Request $r):JsonResponse{$d=$r->validate(['code'=>['required','alpha_dash','max:120','unique:message_templates,code'],'name'=>['required','string','max:180'],'category'=>['required',Rule::in(config('communications.categories',[]))],'subject_template'=>['required','string','max:255'],'body_template'=>['required','string','max:30000'],'channel_overrides'=>['nullable','array'],'governance_status'=>['nullable',Rule::in(['draft','published','retired'])]]);$this->guardSystemCategory($r,$d['category']);$d['created_by']=$r->user()->id;$d['updated_by']=$r->user()->id;return response()->json(['data'=>MessageTemplate::query()->create($d)],201);}
 public function update(Request $r,MessageTemplate $template):JsonResponse{$d=$r->validate(['name'=>['sometimes','string','max:180'],'category'=>['sometimes',Rule::in(config('communications.categories',[]))],'subject_template'=>['sometimes','string','max:255'],'body_template'=>['sometimes','string','max:30000'],'channel_overrides'=>['nullable','array'],'governance_status'=>['sometimes',Rule::in(['draft','published','retired'])]]);$this->guardSystemCategory($r,$d['category']??$template->category);if(in_array($template->category,config('communications.mandatory_categories',[]),true)&&!$r->user()->hasPermission('settings.manage'))abort(403,'System service templates require settings.manage.');$d['updated_by']=$r->user()->id;$template->update($d);return response()->json(['data'=>$template]);}
 private function guardSystemCategory(Request $r,string $category):void{if(in_array($category,config('communications.mandatory_categories',[]),true)&&!$r->user()->hasPermission('settings.manage'))abort(403,'System service templates require settings.manage.');}
}
